version: "3"

tasks:
  extract:
    cmds:
      - python3 el.py -e
  extract-prod:
    cmds:
      - python3 el.py -ep
  load:
    cmds:
      - python3 el.py -l
  load-prod:
    cmds:
      - python3 el.py -lp
  transform:
    cmds:
      - dbt build
  transform-prod:
    cmds:
      - dbt build --target prod
  elt:
    cmds:
      - python3 el.py -el
      - dbt build
  elt-prod:
    cmds:
      - python3 el.py -elp
      - dbt build --target prod
