version: "3"

tasks:
  extract:
    cmds:
      - python3 el.py -e
  extract-prod:
    cmds:
      - python3 el.py -ep
  load:
    cmds:
      - python3 el.py -l
  load-prod:
    cmds:
      - python3 el.py -lp
  transform:
    cmds:
      - dbt deps
      - dbt build
  transform-prod:
    cmds:
      - dbt build --target prod
  elt:
    cmds:
      - python3 el.py -el
      - dbt build
  elt-prod:
    cmds:
      - python3 el.py -elp
      - dbt build --target prod
  setup-bi:
    cmds:
      - npm --prefix ./reports install
  bi:
    cmds:
      - npm run dev --prefix ./reports
  clean:
    cmds:
      - rm -f ./data/*.json.gz 2>/dev/null; exit 0
