version: "3"

tasks:
  setup:
    # only run this inside of a python virtual environment
    - python3 -m pip install --upgrade pip
    - python3 -m pip install -r requirements.txt
    - pre-commit install
    - dbt deps
    - npm install --prefix ./reports
  extract:
    cmds:
      - python3 el.py -e {{.start}} {{.end}}
  load:
    cmds:
      - python3 el.py -l {{.start}} {{.end}}
  load-prod:
    cmds:
      - python3 el.py -lp {{.start}} {{.end}}
  el-prod-incremental:
    cmds:
      - python3 el.py -elpi {{.start}} {{.end}}
  transform:
    cmds:
      - dbt build
  transform-prod:
    cmds:
      - dbt build --target prod
  elt:
    cmds:
      - python3 el.py -eli {{.start}} {{.end}}
      - dbt build
  elt-prod:
    cmds:
      - python3 el.py -elpi {{.start}} {{.end}}
      - dbt build --target prod
  bi:
    cmds:
      - npm run dev --prefix ./reports
  clean:
    cmds:
      - rm -f ./data/*.json.gz 2>/dev/null; exit 0
  generate-fixtures:
    cmds:
      - python3 el.py -e 2023-09-26-10 2023-09-26-10
      - duckdb < generate_fixtures.sql
      - rm ./data/2023-09-26-10.json.gz
